const express = require('express');
const router = express.Router();
const user = require('./controllers/user');
const map = require('./controllers/map');
// app.use("/auth/", authRouter);
router.post('/route/', map.routeMap);
router.post('/services/', map.allServices);
router.post('/serviceroute/', map.routeMapWithServices);
router.post('/user/login', user.login);
router.post('/user/register', user.signup);
router.get('/user/verify/:token', user.verify);
router.post('/user/resetpassword', user.resetPassword);
router.get('/user/reset/:token', user.resetPasswordPage);
router.post('/user/setnewpass/:token', user.setNewPassword);
module.exports = router;
